// PM2 Ecosystem Configuration
// Auto-generated by Wingman - do not edit manually
module.exports = {
  "apps": [
    {
      "name": "honest-ivory-thicket-app-vibes-groups",
      "namespace": "wingman-apps",
      "script": "bash",
      "args": [
        "-c",
        "set -a; [ -f .env ] && . ./.env; set +a; APP_ID='96ee843d-d3bb-46e3-86fb-81be0a2a6bad' APP_LABEL='vibes-groups' USER_ALIAS='honest-ivory-thicket' npx serve -l 51256"
      ],
      "cwd": "/Users/mini/code/vibe-group",
      "out_file": "/Users/mini/code/vibe-group/apps/logs/honest-ivory-thicket-app-vibes-groups-out.log",
      "error_file": "/Users/mini/code/vibe-group/apps/logs/honest-ivory-thicket-app-vibes-groups-error.log",
      "log_date_format": "YYYY-MM-DD HH:mm:ss",
      "merge_logs": true,
      "autorestart": false,
      "max_restarts": 0,
      "min_uptime": "5s"
    }
  ]
};
